name: lasso
channels:
  - defaults
dependencies:
  - scipy=1.2.1
  - tqdm=4.31.1
  - dask=1.1.1
  - matplotlib=3.0.2
  - pandas=0.24.1
  - pip=19.0.3
  - pip:
    - pydot==1.4.0
    - numpy==1.16.1
    - scikit_learn==0.20.2
    - mlflow==0.9.0.1
    - dask_ml==0.11.0
